### ISSUE TITLE
Sonic and Knuckles - sound effect BD distortion

### ISSUE THREAD

**Issue by James-F2** [jotego/jt12#36]
There is a problem with a certain sound effect in Sonic & Knuckles that sounds like distortion.

Information, samples, and guide how to recreate here:
http://www.atari-forum.com/viewtopic.php?f=115&t=31029&p=375808#p375807

Also reported here:
https://github.com/MiSTer-devel/Genesis_MiSTer/issues/28

**Comment by James-F2** [comment]
It has been confirmed and present on the MiST too.

**Comment by jotego** [comment]
I'll look into it when I'm done working with the Popeye core.

**Comment by James-F2** [comment]
This is the most accurate YM2612 in c:
https://github.com/nukeykt/Nuked-OPN2
He also has PSG.

His work is used in DOSBox, Genesis Plus GX and more.

**Comment by jotego** [comment]
Yes, I know.

**Comment by greyrogue** [comment]
Just a couple of comments related to the change I made in MiSTer:
I hadn't intended it to be the final solution.  It was just a stopgap, with comments so you could fix it how you think is best, then MiSTer could merge to your latest.
The issues I saw:
[https://github.com/jotego/jt12/blob/master/hdl/jt12_acc.v#L103](url)
- I believe using left/right there is a typo.  It should be adding 25% of pre_left/pre_right.
- The other issue is that the current code is adding the total number of operators (24 = 4 each for 6 channels) rather than just 6 values (1 for each channel).  This allows the accumulator to reach max value (it is limited correctly already).  This means multiplying by 8/6 is incorrect.  However, if the code is changed to limit each channel to the max value for one operator, than the addition would be correct.  I wasn't sure which was correct, or if you did this on purpose (there are some cases where it might sound better), so I just dropped the addition for now.  This will need to be readdressed after deciding on the max channel value.
https://github.com/jotego/jt12/blob/master/hdl/mixer/jt12_fm_uprate.v#L49
- I believe there is also an potential issue in fm_uprate.  If the FM value is already at max, this addition will overflow.  Whether this is an issue or not depends on how the above is handled/scaled.

I'll try to keep updated info on your repository if I find anything else.

Thanks for these modules.  They are great.

**Comment by jotego** [comment]
Hi,
Yes, that was a typo in the accumulator. I have corrected it. Thank you.
The real hardware operated on the channel, thus the limiter will apply to each channel. The current version of the accumulator works on the operators. This leads to a neat implementation but the overflow/clipping behaviour is different. 
In the repository, there are older versions of the accumulator that work on the channel. I don't remember what was the reason to change it, so they may not be bug free. However, you can dig for them and try if that fixes the problem.
I am sorry I am distracted now with other cores. You are welcome to submit pull requests. Apologies if I sounded too harsh about commits on the MiSTer FPGAgen copy. I understand now that it is a good place to try things. I am just worried about loosing track of an important change that may affect other JT12 users.
